when:
  event: push
  branch:
    - master
    
steps:
  build:
    image: node
    commands:
      - npm i --legacy-peer-deps
      - npm run build
      - cp -r build/* /site
    volumes:
      - /var/www/sites/ttgo.trex.zone:/site

