pipeline:
  build:
    image: node
    commands:
      - npm i --legacy-peer-deps
      - npm run build
      - mv -f build/* /site
    volumes:
      - /var/www/sites/ttgo.trex.zone:/site

branches: 
  - main
